### ISSUE TITLE
Add "info" color palette

### ISSUE THREAD

**Issue by clrux** [edx/ux-pattern-library#119]
We have error, warning, and success color palettes, but we should consider adding one for "info" too (usually a nice mix of blues).

cc @talbs

**Comment by talbs** [comment]
@clrux, thanks - remember that we're trying to collect this type of backlog of ideas/issues in one place. Would you mind creating a JIRA story for this scoped ideas? I'm fine with having GH issues on top of JIRA tickets, but we should start where the rest of our work is.

**Comment by talbs** [comment]
Moving this issue to our UXPL JIRA project - https://openedx.atlassian.net/browse/UXPL-11 for better tracking/prioritization. Closing this issue and following up on next steps there.
