### ISSUE TITLE
Broken links in the Readme

### ISSUE THREAD

**Issue by mcanthony** [edx/ux-pattern-library#17]
The links lead to 404, and pertain to the website to view the working demo. This link may now be irrelevant as the working product has been released, in which case the links might be better removed.

**Comment by clrux** [comment]
@mcanthony Thanks for the heads-up. Would you mind providing me with some context or a link or example where you're seeing a broken link?

**Comment by talbs** [comment]
@mcanthony, thanks for the heads up and our apologies for any troubles the broken preview links caused you. I've created a quick PR to correct those - https://github.com/edx/ux-pattern-library/pull/37.

In case you need access now, you can view our documentation/preview site (powered by Jekyll and gh-pages) at http://ux.edx.org. We're incrementally releasing newer patterns.

Let us know if you have any other trouble or questions about the work. Thanks again for your help!
