### ISSUE TITLE
Sample links have invalid href value (#)

### ISSUE THREAD

**Issue by cptvitamin** [edx/ux-pattern-library#175]
What do you think of changing the href values of the sample links to a valid value?  Currently, they reference "#".  What if they referenced http://ux.edx.org or http://edx.org or self-referenced the parent container /elements/headings/ or #headings ?

**Comment by clrux** [comment]
Or even points to http://www.example.com. I agree.

**Comment by talbs** [comment]
@cptvitamin, thanks for the good feedback. I think https://github.com/edx/ux-pattern-library/pull/179 should resolve all cases (I scoured our templates for any ``href=""`` or ``href="#"`` attributes.
