### ISSUE TITLE
Giving an example of a link as a button promotes bad practice

### ISSUE THREAD

**Issue by cptvitamin** [edx/ux-pattern-library#182]
I noticed that we have examples for creating a hyperlink that appears to be a button.  I'm OK with doing this but it would be a great opportunity to warn developers to do this with care.  Links and Buttons are two different elements with different purposes and even different default controls (Enter/Return is used to activate a link and Space **and** Enter/Return is used to activate a button).  For screen reader users, they appear in different out of context lists.  For example, if a user is getting phone support, the support person would likely tell them to "Click on the login button" (a login button that was actually a link that looked like a button).  They wouldn't find it in their list of buttons.

As a general rule of thumb: "Links go somewhere.  Buttons do something."

**Comment by talbs** [comment]
Thanks, @cptvitamin. Good thoughts!

We're tracking features, ideas, issues, and the like through our Open Source JIRA UXPL project. I've added the details shared here to https://openedx.atlassian.net/browse/UXPL-12 and will follow-up with you on that thread.

**Comment by talbs** [comment]
@cptvitamin, I finally got around to addressing this good feedback. Sorry for the wait. I pinged you on an open PR (https://github.com/edx/ux-pattern-library/pull/245). Mind reviewing?
