### ISSUE TITLE
Contrast of placeholders is too low for all form inputs

### ISSUE THREAD

**Issue by bguertin** [edx/ux-pattern-library#356]
![contrast](https://cloud.githubusercontent.com/assets/1685613/17414046/d0c87224-5a51-11e6-9906-cbc60d03f6fc.png)

**Comment by bjacobel** [comment]
@bguertin Is there a Jira ticket for this issue?

**Comment by bguertin** [comment]
> Is there a Jira ticket for this issue?

None that I can find.

**Comment by bjacobel** [comment]
We don't accept UXPL issues via Github Issues, if you could [create a Jira ticket for this](https://github.com/edx/ux-pattern-library/blob/master/README.md#bugs-and-issues) it would be great.

**Comment by bguertin** [comment]
> We don't accept UXPL issues via Github Issues

Ah, it might be prudent to disable GitHub issues for this repository in that case.

As for the placeholder issue, I suppose it will be made obsolete by https://openedx.atlassian.net/projects/UXPL/issues/UXPL-37
