### ISSUE TITLE
BrowserSync to update with template and script changes

### ISSUE THREAD

**Issue by clrux** [edx/ux-pattern-library#53]
Currently, any changes to the post, markup, or JS files require you to stop and restart the server manually. Can we have it watch and refresh automatically for these just as it does for CSS?

**Comment by talbs** [comment]
Hey, yeah! We can do that. Feel free to try your hand at it yourself, @clrux. The files you want to adjust are:

* https://github.com/edx/ux-pattern-library/blob/master/gulp/tasks/watch.js - this is the watch task that looks for changes in certain directories/configured spots.
* https://github.com/edx/ux-pattern-library/blob/master/gulp%2Fconfig.js - this is the config file where we abstract all of our file paths/settings (in case you need to adjust anything).

**Comment by clrux** [comment]
This is done.
