### ISSUE TITLE
Sass extends don't work properly when compiling with pseudo elements

### ISSUE THREAD

**Issue by clrux** [edx/ux-pattern-library#88]
When creating an extend to use in form field pseudo elements (i.e., `&::-webkit-slider-runnable-track`) the extend doesn't work when used more than once. We need to explore this further and investigate why Sass extends aren't working.

We're using mixins as a temporary solution.

**Comment by talbs** [comment]
Moving this issue to our UXPL JIRA project - https://openedx.atlassian.net/browse/UXPL-9 for better tracking/prioritization. Closing this issue and following up on next steps there.
